language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION="dev-master symfony/debug:~2.8@dev symfony/http-kernel:~2.8@dev"

before_script:
  - phpenv config-add myphp.ini
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer update --no-interaction --prefer-source
  - ./src/BeSimple/SoapClient/Tests/bin/phpwebserver.sh
  - ./src/BeSimple/SoapClient/Tests/bin/axis.sh

script:
  - phpunit --coverage-text

matrix:
  allow_failures:
    - env: SYMFONY_VERSION="dev-master symfony/debug:~2.8@dev symfony/http-kernel:~2.8@dev"
